server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://115.28.131.98:3306
    username: cell
    password: lh02203991
    driver-class-name: com.mysql.cj.jdbc.Driver
redis:
  host: 115.28.131.98
  port: 6379
  timeout: 2000
  expire: 1000000
  pool:
    max-active: 10
    mac-wait: 1000




